# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(716, 539)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(40, 110, 411, 33))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.cbBox_Mode = QtWidgets.QComboBox(Form)
        self.cbBox_Mode.setGeometry(QtCore.QRect(40, 50, 211, 31))
        self.cbBox_Mode.setObjectName("cbBox_Mode")
        self.cbBox_Mode.addItem("")
        self.cbBox_Mode.addItem("")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 450, 102, 33))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 256, 25))
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 110, 102, 33))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 440, 102, 33))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(580, 440, 102, 33))
        self.pushButton_4.setObjectName("pushButton_4")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 200, 258, 225))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("宋体")
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout.addWidget(self.textBrowser_2)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(430, 190, 258, 225))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.textBrowser = QtWidgets.QTextBrowser(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(590, 40, 102, 33))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 500, 681, 25))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 490, 711, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 150, 721, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(350, 160, 21, 341))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(0, 80, 721, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Form)
        self.line_5.setGeometry(QtCore.QRect(0, 10, 721, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(310, 20, 256, 25))
        self.label_5.setObjectName("label_5")
        self.cbBox_Mode_2 = QtWidgets.QComboBox(Form)
        self.cbBox_Mode_2.setGeometry(QtCore.QRect(310, 50, 211, 31))
        self.cbBox_Mode_2.setObjectName("cbBox_Mode_2")
        self.cbBox_Mode_2.addItem("")
        self.cbBox_Mode_2.addItem("")
        self.cbBox_Mode_2.addItem("")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(610, 110, 102, 33))
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Form)
        self.cbBox_Mode.activated['QString'].connect(Form.cbBox_Mode_Callback)
        self.pushButton.clicked.connect(Form.pB_Callback)
        self.pushButton_2.clicked.connect(Form.pB_2_Callback)
        self.pushButton_3.clicked.connect(Form.pB_3_Callback)
        self.pushButton_4.clicked.connect(Form.pB_4_Callback)
        self.pushButton_5.clicked.connect(Form.pB_5_Callback)
        self.textBrowser_2.textChanged.connect(Form.tB_2_Callbaack)
        self.pushButton_6.clicked.connect(Form.pB_6_Callback)
        self.cbBox_Mode_2.activated['QString'].connect(Form.cbBox_Mode_2_Cakllback)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "中文文本分类器"))
        self.cbBox_Mode.setItemText(0, _translate("Form", "<1>：测试集随机抽取"))
        self.cbBox_Mode.setItemText(1, _translate("Form", "<2>：输入内容识别"))
        self.pushButton.setText(_translate("Form", "清除"))
        self.label_3.setText(_translate("Form", "模式选择"))
        self.pushButton_2.setText(_translate("Form", "输入"))
        self.pushButton_3.setText(_translate("Form", "分类"))
        self.pushButton_4.setText(_translate("Form", "清除"))
        self.label_2.setText(_translate("Form", "文本内容"))
        self.label.setText(_translate("Form", "分类结果"))
        self.pushButton_5.setText(_translate("Form", "抽取"))
        self.label_5.setText(_translate("Form", "模型选择"))
        self.cbBox_Mode_2.setItemText(0, _translate("Form", "<1>：神经网络模型"))
        self.cbBox_Mode_2.setItemText(1, _translate("Form", "<2>：SVM模型"))
        self.cbBox_Mode_2.setItemText(2, _translate("Form", "<3>：简单RNN模型"))
        self.pushButton_6.setText(_translate("Form", "清空"))

